apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default (include "helm-chart.fullname" .) }}
  labels:
    app: {{ include "helm-chart.name" . }}
    stack: {{ .Values.stack | default "dev" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "helm-chart.name" . }}
    stack: {{ .Values.stack | default "dev" }}
