name: Python CI/CD Pipeline with Minikube, Docker, Pulumi, and Helm

on:
  push:
    branches:
      - main
    paths:
      - 'python-app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up Minikube
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start

      - name: Build Docker Image
        run: |
          eval $(minikube docker-env)  # Ensure Minikube's Docker environment is used
          docker build -t hello-python:latest ./python-app
          sleep 15

      - name: Load Docker Image into Minikube
        run: |
          eval $(minikube docker-env)  # Ensure Minikube's Docker environment is used
          docker images  # Verify if the image exists locally in Minikube's registry
          minikube image load hello-python:latest  # Load the image into Minikube's Docker registry

      - name: Activate venv and install dependencies
        run: |
          cd pulumi-deployment
          python -m venv venv
          source venv/bin/activate
          pip install pulumi pulumi_kubernetes
          pip install -r requirements.txt

      - name: Pulumi Preview
        working-directory: pulumi-deployment
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          eval $(minikube docker-env)  # Ensure we are using Minikube's Docker
          source venv/bin/activate
          pulumi stack select dev
          pulumi preview

      - name: Pulumi Up
        working-directory: pulumi-deployment
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          eval $(minikube docker-env)  # Ensure we are using Minikube's Docker
          source venv/bin/activate
          pulumi up --yes
