name: Python CI/CD Pipeline with Minikube, Docker, Pulumi, and Helm

on:
  push:
    branches:
      - main
    paths:
      - 'python-app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v3

      - name: Install Minikube
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Build and Load Docker Image into Minikube
        run: |
          eval $(minikube docker-env)
          docker build -t hello-python:latest ./python-app
          minikube image load hello-python:latest

      - name: Set up and Activate Virtual Environment
        run: |
          cd pulumi-deployment
          python -m venv venv
          source venv/bin/activate
          pip install pulumi pulumi_kubernetes

      - name: Pulumi Preview
        run: |
          cd pulumi-deployment
          source venv/bin/activate
          pulumi stack select dev
          pulumi preview

      - name: Pulumi Up (Deploy)
        run: |
          cd pulumi-deployment
          source venv/bin/activate
          pulumi up --yes
